development: &default
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  database: note_taking
  username: tony
  pool: 12

production: &default
  adapter: postgresql
  host: 127.0.0.1
  port: 5432
  database: note_taking
  username: tony
  pool: 12

test: &test
  adapter: postgresql
  database: note_taking_test<%= ENV['TEST_ENV_NUMBER'] %>

# production:
#   <<: *default
#   database: kayla_production